import {quarterRem} from './rem'

const margin = quarterRem('margin')
const marginTop = quarterRem('marginTop')
const marginBottom = quarterRem('marginBottom')
const marginLeft = quarterRem('marginLeft')
const marginRight = quarterRem('marginRight')

export const margin1 = margin(1)
export const margin2 = margin(2)
export const margin3 = margin(3)
export const margin4 = margin(4)
export const margin5 = margin(5)
export const margin6 = margin(6)
export const margin8 = margin(8)
export const margin10 = margin(10)
export const margin12 = margin(12)
export const margin16 = margin(16)
export const margin20 = margin(20)

export const marginTop1 = marginTop(1)
export const marginTop2 = marginTop(2)
export const marginTop3 = marginTop(3)
export const marginTop4 = marginTop(4)
export const marginTop5 = marginTop(5)
export const marginTop6 = marginTop(6)
export const marginTop8 = marginTop(8)
export const marginTop10 = marginTop(10)
export const marginTop12 = marginTop(12)
export const marginTop16 = marginTop(16)
export const marginTop20 = marginTop(20)

export const marginRight1 = marginRight(1)
export const marginRight2 = marginRight(2)
export const marginRight3 = marginRight(3)
export const marginRight4 = marginRight(4)
export const marginRight5 = marginRight(5)
export const marginRight6 = marginRight(6)
export const marginRight8 = marginRight(8)
export const marginRight10 = marginRight(10)
export const marginRight12 = marginRight(12)
export const marginRight16 = marginRight(16)
export const marginRight20 = marginRight(20)

export const marginBottom1 = marginBottom(1)
export const marginBottom2 = marginBottom(2)
export const marginBottom3 = marginBottom(3)
export const marginBottom4 = marginBottom(4)
export const marginBottom5 = marginBottom(5)
export const marginBottom6 = marginBottom(6)
export const marginBottom8 = marginBottom(8)
export const marginBottom10 = marginBottom(10)
export const marginBottom12 = marginBottom(12)
export const marginBottom16 = marginBottom(16)
export const marginBottom20 = marginBottom(20)

export const marginLeft1 = marginLeft(1)
export const marginLeft2 = marginLeft(2)
export const marginLeft3 = marginLeft(3)
export const marginLeft4 = marginLeft(4)
export const marginLeft5 = marginLeft(5)
export const marginLeft6 = marginLeft(6)
export const marginLeft8 = marginLeft(8)
export const marginLeft10 = marginLeft(10)
export const marginLeft12 = marginLeft(12)
export const marginLeft16 = marginLeft(16)
export const marginLeft20 = marginLeft(20)

export const center = {marginLeft: 'auto', marginRight: 'auto'}