import {quarterRems} from './rem'

export const quarterRemsMargin = quarterRems('margin')
export const quarterRemsMarginTop = quarterRems('marginTop')
export const quarterRemsMarginRight = quarterRems('marginRight')
export const quarterRemsMarginBottom = quarterRems('marginBottom')
export const quarterRemsMarginLeft = quarterRems('marginLeft')

export const margin1 = quarterRemsMargin(1)
export const margin2 = quarterRemsMargin(2)
export const margin3 = quarterRemsMargin(3)
export const margin4 = quarterRemsMargin(4)
export const margin5 = quarterRemsMargin(5)
export const margin6 = quarterRemsMargin(6)
export const margin8 = quarterRemsMargin(8)
export const margin10 = quarterRemsMargin(10)
export const margin12 = quarterRemsMargin(12)
export const margin16 = quarterRemsMargin(16)
export const margin20 = quarterRemsMargin(20)

export const marginTop1 = quarterRemsMarginTop(1)
export const marginTop2 = quarterRemsMarginTop(2)
export const marginTop3 = quarterRemsMarginTop(3)
export const marginTop4 = quarterRemsMarginTop(4)
export const marginTop5 = quarterRemsMarginTop(5)
export const marginTop6 = quarterRemsMarginTop(6)
export const marginTop8 = quarterRemsMarginTop(8)
export const marginTop10 = quarterRemsMarginTop(10)
export const marginTop12 = quarterRemsMarginTop(12)
export const marginTop16 = quarterRemsMarginTop(16)
export const marginTop20 = quarterRemsMarginTop(20)

export const marginRight1 = quarterRemsMarginRight(1)
export const marginRight2 = quarterRemsMarginRight(2)
export const marginRight3 = quarterRemsMarginRight(3)
export const marginRight4 = quarterRemsMarginRight(4)
export const marginRight5 = quarterRemsMarginRight(5)
export const marginRight6 = quarterRemsMarginRight(6)
export const marginRight8 = quarterRemsMarginRight(8)
export const marginRight10 = quarterRemsMarginRight(10)
export const marginRight12 = quarterRemsMarginRight(12)
export const marginRight16 = quarterRemsMarginRight(16)
export const marginRight20 = quarterRemsMarginRight(20)

export const marginBottom1 = quarterRemsMarginBottom(1)
export const marginBottom2 = quarterRemsMarginBottom(2)
export const marginBottom3 = quarterRemsMarginBottom(3)
export const marginBottom4 = quarterRemsMarginBottom(4)
export const marginBottom5 = quarterRemsMarginBottom(5)
export const marginBottom6 = quarterRemsMarginBottom(6)
export const marginBottom8 = quarterRemsMarginBottom(8)
export const marginBottom10 = quarterRemsMarginBottom(10)
export const marginBottom12 = quarterRemsMarginBottom(12)
export const marginBottom16 = quarterRemsMarginBottom(16)
export const marginBottom20 = quarterRemsMarginBottom(20)

export const marginLeft1 = quarterRemsMarginLeft(1)
export const marginLeft2 = quarterRemsMarginLeft(2)
export const marginLeft3 = quarterRemsMarginLeft(3)
export const marginLeft4 = quarterRemsMarginLeft(4)
export const marginLeft5 = quarterRemsMarginLeft(5)
export const marginLeft6 = quarterRemsMarginLeft(6)
export const marginLeft8 = quarterRemsMarginLeft(8)
export const marginLeft10 = quarterRemsMarginLeft(10)
export const marginLeft12 = quarterRemsMarginLeft(12)
export const marginLeft16 = quarterRemsMarginLeft(16)
export const marginLeft20 = quarterRemsMarginLeft(20)

export const center = {marginLeft: 'auto', marginRight: 'auto'}