import {quarterRems} from './rem'

export const quarterRemsPadding = quarterRems('padding')
export const quarterRemsPaddingTop = quarterRems('paddingTop')
export const quarterRemsPaddingRight = quarterRems('paddingRight')
export const quarterRemsPaddingLeft = quarterRems('paddingLeft')
export const quarterRemsPaddingBottom = quarterRems('paddingBottom')

export const padding1 = quarterRemsPadding(1)
export const padding2 = quarterRemsPadding(2)
export const padding3 = quarterRemsPadding(3)
export const padding4 = quarterRemsPadding(4)
export const padding5 = quarterRemsPadding(5)
export const padding6 = quarterRemsPadding(6)
export const padding8 = quarterRemsPadding(8)
export const padding10 = quarterRemsPadding(10)
export const padding12 = quarterRemsPadding(12)
export const padding16 = quarterRemsPadding(16)
export const padding20 = quarterRemsPadding(20)

export const paddingTop1 = quarterRemsPaddingTop(1)
export const paddingTop2 = quarterRemsPaddingTop(2)
export const paddingTop3 = quarterRemsPaddingTop(3)
export const paddingTop4 = quarterRemsPaddingTop(4)
export const paddingTop5 = quarterRemsPaddingTop(5)
export const paddingTop6 = quarterRemsPaddingTop(6)
export const paddingTop8 = quarterRemsPaddingTop(8)
export const paddingTop10 = quarterRemsPaddingTop(10)
export const paddingTop12 = quarterRemsPaddingTop(12)
export const paddingTop16 = quarterRemsPaddingTop(16)
export const paddingTop20 = quarterRemsPaddingTop(20)

export const paddingRight1 = quarterRemsPaddingRight(1)
export const paddingRight2 = quarterRemsPaddingRight(2)
export const paddingRight3 = quarterRemsPaddingRight(3)
export const paddingRight4 = quarterRemsPaddingRight(4)
export const paddingRight5 = quarterRemsPaddingRight(5)
export const paddingRight6 = quarterRemsPaddingRight(6)
export const paddingRight8 = quarterRemsPaddingRight(8)
export const paddingRight10 = quarterRemsPaddingRight(10)
export const paddingRight12 = quarterRemsPaddingRight(12)
export const paddingRight16 = quarterRemsPaddingRight(16)
export const paddingRight20 = quarterRemsPaddingRight(20)

export const paddingBottom1 = quarterRemsPaddingBottom(1)
export const paddingBottom2 = quarterRemsPaddingBottom(2)
export const paddingBottom3 = quarterRemsPaddingBottom(3)
export const paddingBottom4 = quarterRemsPaddingBottom(4)
export const paddingBottom5 = quarterRemsPaddingBottom(5)
export const paddingBottom6 = quarterRemsPaddingBottom(6)
export const paddingBottom8 = quarterRemsPaddingBottom(8)
export const paddingBottom10 = quarterRemsPaddingBottom(10)
export const paddingBottom12 = quarterRemsPaddingBottom(12)
export const paddingBottom16 = quarterRemsPaddingBottom(16)
export const paddingBottom20 = quarterRemsPaddingBottom(20)

export const paddingLeft1 = quarterRemsPaddingLeft(1)
export const paddingLeft2 = quarterRemsPaddingLeft(2)
export const paddingLeft3 = quarterRemsPaddingLeft(3)
export const paddingLeft4 = quarterRemsPaddingLeft(4)
export const paddingLeft5 = quarterRemsPaddingLeft(5)
export const paddingLeft6 = quarterRemsPaddingLeft(6)
export const paddingLeft8 = quarterRemsPaddingLeft(8)
export const paddingLeft10 = quarterRemsPaddingLeft(10)
export const paddingLeft12 = quarterRemsPaddingLeft(12)
export const paddingLeft16 = quarterRemsPaddingLeft(16)
export const paddingLeft20 = quarterRemsPaddingLeft(20)