import {quarterRem} from './rem'

const padding = quarterRem('padding')
const paddingTop = quarterRem('paddingTop')
const paddingBottom = quarterRem('paddingBottom')
const paddingLeft = quarterRem('paddingLeft')
const paddingRight = quarterRem('paddingRight')

export const padding1 = padding(1)
export const padding2 = padding(2)
export const padding3 = padding(3)
export const padding4 = padding(4)
export const padding5 = padding(5)
export const padding6 = padding(6)
export const padding8 = padding(8)
export const padding10 = padding(10)
export const padding12 = padding(12)
export const padding16 = padding(16)
export const padding20 = padding(20)

export const paddingTop1 = paddingTop(1)
export const paddingTop2 = paddingTop(2)
export const paddingTop3 = paddingTop(3)
export const paddingTop4 = paddingTop(4)
export const paddingTop5 = paddingTop(5)
export const paddingTop6 = paddingTop(6)
export const paddingTop8 = paddingTop(8)
export const paddingTop10 = paddingTop(10)
export const paddingTop12 = paddingTop(12)
export const paddingTop16 = paddingTop(16)
export const paddingTop20 = paddingTop(20)

export const paddingRight1 = paddingRight(1)
export const paddingRight2 = paddingRight(2)
export const paddingRight3 = paddingRight(3)
export const paddingRight4 = paddingRight(4)
export const paddingRight5 = paddingRight(5)
export const paddingRight6 = paddingRight(6)
export const paddingRight8 = paddingRight(8)
export const paddingRight10 = paddingRight(10)
export const paddingRight12 = paddingRight(12)
export const paddingRight16 = paddingRight(16)
export const paddingRight20 = paddingRight(20)

export const paddingBottom1 = paddingBottom(1)
export const paddingBottom2 = paddingBottom(2)
export const paddingBottom3 = paddingBottom(3)
export const paddingBottom4 = paddingBottom(4)
export const paddingBottom5 = paddingBottom(5)
export const paddingBottom6 = paddingBottom(6)
export const paddingBottom8 = paddingBottom(8)
export const paddingBottom10 = paddingBottom(10)
export const paddingBottom12 = paddingBottom(12)
export const paddingBottom16 = paddingBottom(16)
export const paddingBottom20 = paddingBottom(20)

export const paddingLeft1 = paddingLeft(1)
export const paddingLeft2 = paddingLeft(2)
export const paddingLeft3 = paddingLeft(3)
export const paddingLeft4 = paddingLeft(4)
export const paddingLeft5 = paddingLeft(5)
export const paddingLeft6 = paddingLeft(6)
export const paddingLeft8 = paddingLeft(8)
export const paddingLeft10 = paddingLeft(10)
export const paddingLeft12 = paddingLeft(12)
export const paddingLeft16 = paddingLeft(16)
export const paddingLeft20 = paddingLeft(20)